In [1]:
import numpy as np


In [3]:
import numpy as np

In [7]:
lst=[1,3,4,5,5,6,6,7]
print("type of list",type(lst))
arr=np.array(lst)
print(arr)
print("type of array",type(arr))

type of list <class 'list'>
[1 3 4 5 5 6 6 7]
type of array <class 'numpy.ndarray'>


In [5]:
arr=np.array(list(range(1,21)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [6]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
import numpy as np
arr =np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [1]:
import numpy as np
arr=np.linspace(2,10,20)
arr


array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [10]:
#1d array convert into 2d array
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [4]:
arr=np.arange(1,100)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
arr.reshape.(1,99)


SyntaxError: invalid syntax (1262397253.py, line 1)

In [20]:
arr=np.random.randint(1,5,9)#total element9,starting 1,ending5
arr

array([4, 4, 3, 1, 1, 2, 2, 4, 1], dtype=int32)

In [25]:
arr=np.random.randint(2,4,10)
arr

array([2, 3, 3, 3, 2, 2, 3, 2, 2, 2], dtype=int32)

In [24]:
arr=np.random.randint(1,5,(3,3))
arr

array([[1, 3, 2],
       [4, 3, 4],
       [1, 3, 4]], dtype=int32)

In [15]:
arr=np.random.random(10)
arr

array([0.35909305, 0.29465965, 0.96888745, 0.43489958, 0.6984534 ,
       0.83271072, 0.07579179, 0.06992788, 0.22000211, 0.02597976])

In [16]:
arr=np.random.random((5,10))
arr

array([[0.3516614 , 0.04099241, 0.3459614 , 0.30192314, 0.96743193,
        0.242821  , 0.23351249, 0.73033877, 0.08797589, 0.32837891],
       [0.58230182, 0.50386598, 0.63053292, 0.74980102, 0.35943006,
        0.05053015, 0.26776732, 0.64976494, 0.12464609, 0.49670692],
       [0.78448552, 0.50018229, 0.13475045, 0.3386395 , 0.4166931 ,
        0.50271672, 0.55242738, 0.32449058, 0.33197489, 0.68001958],
       [0.60054817, 0.58280563, 0.41654951, 0.35951583, 0.96432954,
        0.54792847, 0.67786703, 0.65653414, 0.03826121, 0.72650151],
       [0.86734626, 0.02566621, 0.69922122, 0.43038547, 0.15998918,
        0.69841372, 0.39871201, 0.31981798, 0.87476045, 0.98682153]])

In [19]:
arr= np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [20]:
arr.shape
arr.size
print("shape of array",arr.shape)
print("size of array",arr.size)
print("data types:-",arr.dtype)
print("number of dimension",arr.ndim)

shape of array (12, 5)
size of array 60
data types:- int64
number of dimension 2


In [21]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [22]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [23]:
# learn diff of both function


In [24]:
arr.shape

(12, 5)

In [25]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [27]:
arr.T.shape

(5, 12)

In [29]:
arr[5]

array([25, 26, 27, 28, 29])

In [30]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [32]:
arr[0:12]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [33]:
arr[1,1]

np.int64(6)

In [34]:
arr[1,3:5]

array([8, 9])

In [35]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [36]:
arr[1,1]

np.int64(6)

In [38]:
arr[1,1]=100
arr

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [39]:
arr[11,4]

np.int64(59)

In [40]:
arr[-1,-1]

np.int64(59)

In [41]:
arr[11]

array([55, 56, 57, 58, 59])

In [42]:
arr[11][-1]

np.int64(59)

In [81]:
np.array(np.arange(225).reshape(5,15,3))
arr


array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [46]:
arr.ndim,arr.shape,arr.size,arr.argmax

(2, (12, 5), 60, <function ndarray.argmax>)

In [47]:
arr[0,2:]

array([2, 3, 4])

In [49]:
arr[0,2:2]

array([], dtype=int64)

In [77]:
arr[0,3:5]

array([3, 4])

In [83]:
arr[:, 0 ,:]
arr

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [84]:
arr[:,0:1,0:1]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [71]:
arr[0,1,1]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [58]:
np.array([1,5,6,9,2])
arr

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [59]:
np.shot

AttributeError: module 'numpy' has no attribute 'shot'

In [75]:
arr=np.array[(1,2,3,5)]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [62]:
arr1=np.array([1,2,3,5])
arr2=np.array([1,6,3,5])
arr

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [64]:
arr1-arr2

array([ 0, -4,  0,  0])

In [65]:
arr1+arr2

array([ 2,  8,  6, 10])

In [66]:
arr1*arr2

array([ 1, 12,  9, 25])